name: example

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
  SSH_KEYPAIR: ${{secrets.SSH_KEYPAIR}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v4

      -
        name: set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_TOKEN

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: $DOCKER_USERNAME/myapp:latest


